#Site settings
title: Vuel Guevara
description: Thinker // Designer // Developer
email: vuelguevara@gmail.com

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested